name: Static Code Scan

on:
  pull_request:
    paths:
      - '**.js'
      - '**.py'
      - '**.php'
      - 'patterns.yaml'
      - 'scanner.py'
      - '.github/workflows/security.yml'

jobs:
  scan:
    name: Static Scanner
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run static vuln scanner
        run: python scanner.py

      - name: Upload SARIF as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sarif-report
          path: results.sarif

      - name: Upload SARIF to GitHub code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
